### PR TITLE
Ignore usage of DOM related typescript type or interface and performs lint on react component that returns fragments

### PR DESCRIPTION
**Pull request by vietanhtran16**
I have also updated the tests to reflect the two scenarios mentioned in the title

### CODE REVIEW

**Comment by vietanhtran16** [comment]
@kopiro would you be able to review this? Thanks 👍

**Comment by Samywamy10** [comment]
+1 to this change, thanks for writing @vietanhtran16

**Comment by vietanhtran16** [comment]
@kopiro have you had a chance to look at this yet? Thanks

**Comment by kopiro** [comment]
I've cleaned up commits and moved to https://github.com/kopiro/eslint-plugin-ssr-friendly/pull/14

**Comment by kopiro** [comment]
Fixed in `1.0.6`

**Comment by vietanhtran16** [comment]
awesome thank you 👍

**Pull request closed without merging**
